# Generated by Django 4.0.6 on 2022-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcaterapp', '0004_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
