# Generated by Django 4.0.6 on 2022-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcaterapp', '0007_alter_post_author_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
