# Generated by Django 4.0.6 on 2022-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcaterapp', '0008_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
